stages:
  - test

.phpstan: &phpstan
  image: php:8.1
  stage: test
  before_script:
    - apt-get update && apt-get install -y curl unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
    - composer require --dev nette/di "${NETTE_DI_VERSION}"
  script:
    - vendor/bin/phpstan analyse

phpstan-nette-di-3.0:
  <<: *phpstan
  variables:
    NETTE_DI_VERSION: ^3.0

phpstan-nette-di-2.4:
  <<: *phpstan
  variables:
    NETTE_DI_VERSION: ^2.4

phpstan-nette-di-2.3:
  <<: *phpstan
  variables:
    NETTE_DI_VERSION: ^2.3
