stages:
  - test

phpstan:
  image: php:8.1
  stage: test
  before_script:
    - apt-get update && apt-get install -y curl unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
    - composer require --dev nette/di "^3.0"
  script:
    - vendor/bin/phpstan analyse
